import { z } from 'zod';
import { AgentEnvelopeBase, Confidence, EvidenceRef } from './common';

export const AccountHunterOutput = AgentEnvelopeBase.extend({ accounts:z.array(z.object({brandName:z.string(),domain:z.string(),country:z.string().optional(),sector:z.string().optional(),sourceUris:z.array(z.string().url()).min(1),fitHints:z.array(z.string()).default([])})) });
export const ResearchOutput = AgentEnvelopeBase.extend({ dossier:z.object({summary:z.string(),digitalAssets:z.array(z.string()),initiatives:z.array(z.string()),sourceCoverage:z.number().min(0).max(1)}) });
export const AccessibilityIntelligenceOutput = AgentEnvelopeBase.extend({ signals:z.array(z.object({type:z.string(),severity:z.enum(['info','low','medium','high']),description:z.string(),evidenceIds:z.array(z.string().uuid()),scanIsIndicator:z.literal(true)})), opportunityScore:z.number().min(0).max(100), disclaimer:z.string() });
export const BuyingCommitteeOutput = AgentEnvelopeBase.extend({ contacts:z.array(z.object({name:z.string(),title:z.string().optional(),department:z.string().optional(),role:z.enum(['DECISION_MAKER','CHAMPION','INFLUENCER','TECHNICAL','PROCUREMENT','LEGAL','UNKNOWN']),channel:z.object({type:z.enum(['EMAIL','LINKEDIN','PHONE']),address:z.string(),verified:z.boolean()}),confidence:Confidence,sourceEvidenceIds:z.array(z.string().uuid())})) });
export const ScoringOutput = AgentEnvelopeBase.extend({ score:z.number().min(0).max(100),priority:z.enum(['A','B','C','BELOW_THRESHOLD']),factors:z.record(z.number().min(0).max(100)),explanation:z.array(z.string()) });
export const MessageAngleOutput = AgentEnvelopeBase.extend({ angle:z.object({name:z.string(),personaRelevance:z.string(),problemFrame:z.string(),cta:z.string(),evidenceIds:z.array(z.string().uuid())}),alternatives:z.array(z.string()).max(3) });
export const PersonalizationWriterOutput = AgentEnvelopeBase.extend({ draft:z.object({subject:z.string().max(100).optional(),body:z.string().min(1),language:z.enum(['pt-BR','es','en']),evidenceIds:z.array(z.string().uuid()),knowledgeItemIds:z.array(z.string().uuid()),claims:z.array(z.object({text:z.string(),support:z.array(EvidenceRef)}))}) });
export const OutreachSchedulerOutput = AgentEnvelopeBase.extend({ nextAction:z.object({actionType:z.string(),scheduledAt:z.string().datetime(),channel:z.enum(['EMAIL','LINKEDIN','PHONE','INTERNAL']),reason:z.string()}).nullable() });
export const ReplyClassifierOutput = AgentEnvelopeBase.extend({ classification:z.object({intent:z.enum(['UNKNOWN','NEUTRAL','INTERESTED','POSITIVE_REPLY','READY_TO_BUY','REQUEST_INFO','REQUEST_DEMO','REQUEST_MEETING','OBJECTION','NOT_NOW','NOT_INTERESTED','OPT_OUT','PROCUREMENT','LEGAL','SECURITY','PRICING']),sentiment:z.enum(['POSITIVE','NEUTRAL','NEGATIVE','MIXED','UNKNOWN']),objectionType:z.string().nullable(),requiresHuman:z.boolean(),pauseSequence:z.literal(true)}) });
export const ReplyComposerOutput = AgentEnvelopeBase.extend({ draft:z.object({body:z.string(),language:z.enum(['pt-BR','es','en']),actionClass:z.enum(['GREEN','YELLOW','RED']),knowledgeItemIds:z.array(z.string().uuid()),evidenceIds:z.array(z.string().uuid())}).nullable(),escalationReason:z.string().nullable() });
export const QualificationOutput = AgentEnvelopeBase.extend({ qualification:z.object({fit:z.boolean(),relevantPerson:z.boolean(),need:z.string().nullable(),scope:z.object({domains:z.number().int().nonnegative().optional(),channels:z.array(z.string()).default([]),description:z.string().optional()}),engagement:z.enum(['none','neutral','positive','high']),timing:z.string().nullable(),blockers:z.array(z.string()),missingFields:z.array(z.string()),isSql:z.boolean(),handoffReason:z.string().nullable(),nextQuestion:z.string().nullable()}) });
export const MeetingCoordinatorOutput = AgentEnvelopeBase.extend({ action:z.enum(['PROPOSE_SLOTS','BOOK','ESCALATE']),slots:z.array(z.string().datetime()).max(5),timezone:z.string(),meetingTitle:z.string().optional(),participants:z.array(z.string()).default([]),escalationReason:z.string().nullable() });
export const MeetingPrepOutput = AgentEnvelopeBase.extend({ brief:z.object({executiveSummary:z.string(),participants:z.array(z.object({name:z.string(),role:z.string().optional()})),history:z.array(z.string()),verifiedFacts:z.array(z.object({claim:z.string(),evidenceId:z.string().uuid()})),hypotheses:z.array(z.string()),objectives:z.array(z.string()),questions:z.array(z.string()),likelyObjections:z.array(z.string()),recommendedOffer:z.string().nullable(),risks:z.array(z.string()),doNotSay:z.array(z.string())}) });
export const CrmSyncOutput = AgentEnvelopeBase.extend({ operations:z.array(z.object({object:z.enum(['COMPANY','CONTACT','DEAL','NOTE','ACTIVITY']),operation:z.enum(['CREATE','UPDATE','NOOP','CONFLICT']),externalId:z.string().nullable(),fields:z.record(z.unknown()),authoritativeConflicts:z.array(z.string()).default([])})) });
export const AiSupervisorOutput = AgentEnvelopeBase.extend({ verdict:z.enum(['PASS','REVIEW','BLOCK']),unsupportedClaims:z.array(z.string()),staleEvidenceIds:z.array(z.string().uuid()),genericityScore:z.number().min(0).max(1),personalizationScore:z.number().min(0).max(1),policyRisk:z.enum(['GREEN','YELLOW','RED']),requiredApproval:z.boolean(),reasons:z.array(z.string()) });
export const LearningAnalystOutput = AgentEnvelopeBase.extend({ proposals:z.array(z.object({type:z.enum(['PROMPT','WEIGHT','THRESHOLD','PLAYBOOK','SEQUENCE']),currentVersion:z.string(),proposal:z.string(),evidence:z.array(z.string()),expectedImpact:z.string(),risk:z.enum(['LOW','MEDIUM','HIGH']),requiresOfflineEval:z.literal(true)})) });

export const AgentSchemas = {
  account_hunter: AccountHunterOutput, research_agent: ResearchOutput, accessibility_intelligence: AccessibilityIntelligenceOutput,
  buying_committee_mapper: BuyingCommitteeOutput, scoring_agent: ScoringOutput, message_angle_agent: MessageAngleOutput,
  personalization_writer: PersonalizationWriterOutput, outreach_scheduler: OutreachSchedulerOutput, reply_classifier: ReplyClassifierOutput,
  reply_composer: ReplyComposerOutput, qualification_agent: QualificationOutput, meeting_coordinator: MeetingCoordinatorOutput,
  meeting_prep_agent: MeetingPrepOutput, crm_sync_agent: CrmSyncOutput, ai_supervisor: AiSupervisorOutput, learning_analyst: LearningAnalystOutput,
} as const;
